<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Add Files</name>
   <tag></tag>
   <elementGuidId>5ebc52c4-174e-429d-8af9-819cf5401684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Add Files']//following-sibling::input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#addBtn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a3f39b34-d8f7-4977-88f4-fd2f900eaf13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>1i1n1v479u9vu91qv7eichn01</value>
      <webElementGuid>8ad59dbe-7343-4677-8e62-43e0b4308528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fup-picker-label button btn btn-primary</value>
      <webElementGuid>3318e955-2a36-4f94-bb4e-87c18f5c1f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addBtn</value>
      <webElementGuid>03810a1d-8872-413f-8172-a0873924d48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Files</value>
      <webElementGuid>26aff3f3-ec78-4482-9881-77ec08d36030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addBtn&quot;)</value>
      <webElementGuid>1e59be2f-3f6c-497f-8bc5-40aa93b89ccf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='addBtn']</value>
      <webElementGuid>ffdd803f-3499-4abe-a5b1-45cec73f7336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filemailuploadercontainer']/div/label</value>
      <webElementGuid>fd9ff0fa-3c11-4344-9554-4b23cf215a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make sure that all uploaded files are not renamed or removed while the upload is pending.'])[1]/following::label[1]</value>
      <webElementGuid>6aad9865-739c-4a70-8807-0e0a5a426feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select files to be uploaded.'])[1]/following::label[1]</value>
      <webElementGuid>d66ff285-1653-40c3-b625-bfae9e57b493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Folder'])[1]/preceding::label[1]</value>
      <webElementGuid>37906941-0891-4bd3-bbde-0fab4d061db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>f55083ea-5873-4d5b-b6c9-cdca5652be7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'addBtn' and (text() = 'Add Files' or . = 'Add Files')]</value>
      <webElementGuid>0d189858-a771-4b97-a758-e06bf3423f30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
